import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import test from 'node:test';
import pg from 'pg';
import {Store} from '../src/store.js';
import {PgAuthStore,migrateAuth} from '../src/auth-store.js';
import {createAuth} from '../src/auth.js';
import {createDemoAdapters} from '../src/demo.js';
import {createApiServer} from '../src/http.js';
import {goalSchema,sessionSchema} from '@herbie/contracts';

test('HTTP sessions protect durable goals, preserve idempotency and enforce cookie origin checks',async t=>{
  const database=process.env.HERBIE_TEST_DATABASE_URL;
  if(!database) return t.skip('Set HERBIE_TEST_DATABASE_URL for real PostgreSQL integration');
  const schema=`http_${randomUUID().replaceAll('-','')}`;
  const admin=new pg.Pool({connectionString:database});
  await admin.query(`CREATE SCHEMA ${schema}`);
  const pool=new pg.Pool({connectionString:database,options:`-c search_path=${schema}`});
  const store=new Store(pool); await store.migrate(); await migrateAuth(pool);
  const auth=createAuth({mode:'demo',publicUrl:'http://localhost:8787',credentialKey:Buffer.alloc(32,7).toString('base64')},new PgAuthStore(pool));
  const server=createApiServer({store,auth,adapters:createDemoAdapters(),publicUrl:'http://localhost:8787'});
  t.after(async()=>{await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();});
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
  const address=server.address(); assert.ok(address&&typeof address==='object');
  const base=`http://127.0.0.1:${address.port}`;
  assert.equal((await fetch(`${base}/api/goals`)).status,401);
  const login=await fetch(`${base}/api/demo/login`,{method:'POST',headers:{'content-type':'application/json',origin:'http://localhost:8787'},body:'{}'});
  assert.equal(login.status,200);sessionSchema.parse(await login.json());
  const cookie=login.headers.get('set-cookie')?.split(';')[0];assert.ok(cookie);
  const input={repository:'demo/example',prompt:'Make addition correct',testCommand:['node','--test'],maxAttempts:2};
  const key=randomUUID();
  const headers={'content-type':'application/json',cookie,'idempotency-key':key};
  assert.equal((await fetch(`${base}/api/goals`,{method:'POST',headers,body:JSON.stringify(input)})).status,403);
  const request=()=>fetch(`${base}/api/goals`,{method:'POST',headers:{...headers,origin:'http://localhost:8787'},body:JSON.stringify(input)});
  const first=await request();assert.equal(first.status,201);const goal=goalSchema.parse(await first.json());
  const replay=await request();assert.equal(replay.status,200);assert.equal(goalSchema.parse(await replay.json()).id,goal.id);
  const paused=await fetch(`${base}/api/goals/${goal.id}/pause`,{method:'POST',headers:{cookie,origin:'http://localhost:8787'}});
  assert.equal(goalSchema.parse(await paused.json()).state,'paused');
  const cancel=()=>fetch(`${base}/api/goals/${goal.id}/cancel`,{method:'POST',headers:{cookie,origin:'http://localhost:8787'}});
  assert.equal(goalSchema.parse(await (await cancel()).json()).state,'cancelled');
  assert.equal(goalSchema.parse(await (await cancel()).json()).state,'cancelled');
  assert.equal((await fetch(`${base}/api/goals/${randomUUID()}`,{headers:{cookie}})).status,404);
});
