/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: d6f2cc4017e8d777736afda467b655da)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ORIGIN: string;
	DAYTONA_SNAPSHOT: string;
	CODEX_MODEL: string;
	FACTORY_ENABLED: string;
	GITHUB_APP_ID: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_APP_SLUG: string;
	ALLOWED_EMAIL_DOMAINS: string;
	EMAIL_FROM: string;
	MAILGUN_DOMAIN: string;
	MAILGUN_REGION: string;
	GOALS: DurableObjectNamespace<import("./src/cloudflare/worker").GoalCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cloudflare/worker");
		durableNamespaces: "GoalCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "DAYTONA_SNAPSHOT" | "CODEX_MODEL" | "FACTORY_ENABLED" | "GITHUB_APP_ID" | "GITHUB_CLIENT_ID" | "GITHUB_APP_SLUG" | "ALLOWED_EMAIL_DOMAINS" | "EMAIL_FROM" | "MAILGUN_DOMAIN" | "MAILGUN_REGION">> {}
}
