/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 7561b608944563d63ccb77db3dc26de0)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ORIGIN: string;
	GOOGLE_CLIENT_ID: string;
	DAYTONA_SNAPSHOT: string;
	CODEX_MODEL: string;
	FACTORY_ENABLED: string;
	GITHUB_APP_ID: string;
	GOALS: DurableObjectNamespace<import("./src/cloudflare/worker").GoalCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cloudflare/worker");
		durableNamespaces: "GoalCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "GOOGLE_CLIENT_ID" | "DAYTONA_SNAPSHOT" | "CODEX_MODEL" | "FACTORY_ENABLED" | "GITHUB_APP_ID">> {}
}
